export default function TermsPage() {
    return (
        <div className="p-8 max-w-4xl mx-auto bg-black min-h-screen text-zinc-400 overflow-y-auto pb-32 text-sm leading-relaxed text-justify">
            <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
            <p className="mb-8 text-xs text-zinc-500 uppercase tracking-widest">Last Updated: December 25, 2025</p>

            <section className="mb-8">
                <h2 className="text-lg font-bold text-zinc-200 mb-3 border-b border-zinc-800 pb-2">1. Acceptance of the Terms</h2>
                <p className="mb-4">
                    These Terms of Service ("Terms") constitute a legally binding agreement between you ("User") and AskAnaliz ("Company") governing your access to and use of the AskAnaliz platform, website, and associated applications (collectively, the "Service"). By creating an account, accessing, or using the Service, you signify your irrevocable acceptance of these Terms. If you do not agree to be bound by these Terms in their entirety, you are expressly prohibited from using the Service.
                </p>
            </section>

            <section className="mb-8">
                <h2 className="text-lg font-bold text-zinc-200 mb-3 border-b border-zinc-800 pb-2">2. Nature of Services & Disclaimers</h2>
                <p className="mb-4">
                    The Service utilizes advanced artificial intelligence algorithms to generate feedback based on user input. <strong>THE SERVICE IS INTENDED SOLELY FOR ENTERTAINMENT AND INFORMATIONAL PURPOSES.</strong> The Company does not provide medical, psychological, legal, or financial advice. The outputs generated by the Service should not be interpreted as professional counsel. You acknowledge and agree that reliance on any information provided by the Service is solely at your own risk.
                </p>
            </section>

            <section className="mb-8">
                <h2 className="text-lg font-bold text-zinc-200 mb-3 border-b border-zinc-800 pb-2">3. User Obligations & Conduct</h2>
                <p className="mb-4">
                    You agree to use the Service only for lawful purposes. You represent that you are at least 18 years of age. You are strictly prohibited from: (i) transmitting any content that is infringing, libelous, defamatory, obscene, or otherwise objectionable; (ii) reverse engineering, decompiling, or attempting to derive the source code of the Service; and (iii) using automated scripts or bots to access the Service. Verification of compliance is subject to the Company’s sole discretion.
                </p>
            </section>

            <section className="mb-8">
                <h2 className="text-lg font-bold text-zinc-200 mb-3 border-b border-zinc-800 pb-2">4. Intellectual Property Rights</h2>
                <p className="mb-4">
                    All intellectual property rights in the Service, including but not limited to software, algorithms, designs, text, and graphics, are owned by or licensed to the Company. Nothing in these Terms grants you any right, title, or interest in the Company’s intellectual property, except for the limited, non-exclusive, non-transferable license to access the Service for personal use.
                </p>
            </section>

            <section className="mb-8">
                <h2 className="text-lg font-bold text-zinc-200 mb-3 border-b border-zinc-800 pb-2">5. Limitation of Liability</h2>
                <p className="mb-4 uppercase font-medium border-l-2 border-red-500/50 pl-4 py-1">
                    TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THE USE OF, OR INABILITY TO USE, THE SERVICE.
                </p>
            </section>

            <section className="mb-8">
                <h2 className="text-lg font-bold text-zinc-200 mb-3 border-b border-zinc-800 pb-2">6. Indemnification</h2>
                <p className="mb-4">
                    You agree to defend, indemnify, and hold harmless the Company and its officers, directors, employees, and agents from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the Service; (ii) your violation of any term of these Terms; or (iii) your violation of any third-party right, including without limitation any copyright, property, or privacy right.
                </p>
            </section>

            <section className="mb-8">
                <h2 className="text-lg font-bold text-zinc-200 mb-3 border-b border-zinc-800 pb-2">7. Governing Law</h2>
                <p className="mb-4">
                    These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which the Company is established, without regard to its conflict of law provisions. Any dispute arising from these Terms shall be resolved exclusively in the competent courts of said jurisdiction.
                </p>
            </section>
        </div>
    );
}
